spring:
  application:
    name: platform-demo

  data:
    rest:
      basePath: /api
    cassandra:
      keyspace-name: ${vcap.services.cassandra-db.credentials.keyspace:demo}
      contact-points: ${vcap.services.cassandra-db.credentials.uri:localhost}

---
spring:
  profiles: mesos
  data:
    cassandra:
      contact-points: cassandra-dcos-node.cassandra.dcos.mesos

